# Generated by Django 5.1.3 on 2025-07-25 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='patient_reports/')),
                ('report_title', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='api.dicomdata')),
            ],
        ),
    ]
