# Generated by Django 5.1.3 on 2025-07-25 10:10

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patientreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='report_file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='patient_reports/'),
        ),
    ]
