# Generated by Django 5.1.3 on 2025-07-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patientreport_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='report_file',
            field=models.FileField(upload_to='patient_reports/'),
        ),
    ]
