# Generated by Django 5.1.3 on 2025-09-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patientreport_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='can_edit_contrast_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_inhouse_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='can_edit_is_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='contrast_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='imaging_views',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='inhouse_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dicomdata',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
