# Generated by Django 5.1.3 on 2025-09-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_can_edit_contrast_used_client_can_edit_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='cardiologist',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='cardiologists',
            field=models.ManyToManyField(blank=True, to='api.personalinfo'),
        ),
    ]
