# Generated by Django 5.1.3 on 2025-09-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_patientdetails_cardiologist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='cardiologists',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='cardiologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personalinfo'),
        ),
    ]
