# Generated by Django 5.1.3 on 2025-09-24 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ecgclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.date'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecg_jpgs/'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='reportimage',
            field=models.FileField(blank=True, null=True, upload_to='ecg_graphs/'),
        ),
    ]
