# Generated by Django 5.1.3 on 2025-09-24 09:07

import django.db.models.deletion
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_patientdetails_date_alter_patientdetails_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='date',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.date'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecg_jpgs/'),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='reportimage',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecg_graphs/'),
        ),
    ]
